/**
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 *
 * Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
 * Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
 * Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
 *
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 * @task 045
 * @answer 1533776805
 */
#include "../projecteuler.h"

UI solve045() {
    set<UI> T, P, H;
    UI t = 1, p = 1, h = 1;

    bool cont = true;
    while (cont) {
        UI min = (UI)1e9;
        F(i,100) {
            UI nextH = h * (2 * h - 1);
            H.insert(nextH);
            h++;

            UI nextP = p * (3 * p - 1) / 2;
            P.insert(nextP);
            p++;

            min = MIN(nextP, nextH);
        }

        UI nextT;
        do {
            nextT  = t * (t + 1) / 2;
            if (INSET(P, nextT) && INSET(H, nextT) && t > 285) {
                //TRACE(t);
                return nextT;
            }
            t++;
        } while (nextT < min);
        t--;
    }

    return 0;
}

int main() {
    cout << solve045();
    return 0;
}
